import 'package:path_provider/path_provider.dart';


// Generated by objectbox_generator.
import 'package:test_task/objectbox.g.dart';

import 'dtos/service_dto.dart';

class ObjectBoxStore {
  ObjectBoxStore({
    required this.store,
    required this.serviceBox,
  });

  final Store store;
  final Box<ServiceDto> serviceBox;
}

Future<ObjectBoxStore> initObjectBoxStore({String path = 'mobile_app'}) async {
  final directory = await getApplicationDocumentsDirectory();
  final store = Store(
    getObjectBoxModel(),
    directory: '${directory.path}/$path',
  );

  return ObjectBoxStore(
    store: store,
    serviceBox: store.box<ServiceDto>(),
  );
}

